### ISSUE TITLE
Project Undockerization

### ISSUE THREAD

**Issue by Starz0r** [parrot-translate/parrot#79]
I'd like to be able to work on this project as stated here: https://github.com/anthonynsimon/parrot/issues/66
but the tight dockerization of this project makes it a high barrier of entry to use for people who are unfamiliar with Docker, or don't want to use Docker to try it out. Having a Docker Image for this project I think is a great goal (but the one on hub.docker.com) doesn't even work.

The biggest problem so far with myself trying to do this, is that the web frontend is almost completely integrated with Docker because of NGINX and not being able to turn of TLS. If I could just run the web frontend from the Angular CLI or, serve it from another reverse proxy without running into Preflight Request issues, then I'll actually be able to get somewhere.

Another thing is you need to completely disable generating certs or anything related to TLS for right now. HTTPS adoption is at it's highest because the amount of tools that make it easy to do, I don't need the software doing it for me. While some people may do, we can re-add it in, or cross that bridge when we get there.

Scripts are also Unix only, so if someone wants to try it out on Linux, they'll have to do so through WSL, or a bash shell like Cygwin, or MSYS2. Depending on what they do, we could probably write a cross-platform build script to do this so it won't have to be worried about.

Breaking up the project into multiple repositories would probably improve organization by a lot. Having the web frontend and the API backend share the same repository space can be a huge productivity killer, not to mention it's just messy.

I can see huge potential for this project, but only if a lot of this mess can be sorted out. From what I tried in Docker, it seems really good so far, and would be an excellent addition to self-hosted projects if we could get to v1.

**Comment by anthonynsimon** [comment]
@Starz0r Hey sorry for taking a while, unfortunately there are not as many contributors to the project at the moment, but I was able to kick start the effort to 'undockerize' the project. See #80 for the changes implemented so far.

**Comment by Starz0r** [comment]
@anthonynsimon Is there a way I can contact you directly? Doing it through Github is really slow. All the changes you made look fairly reasonable, and might it possible for me to work on it and test other changes.

**Comment by anthonynsimon** [comment]
@Starz0r I created a chat on gitter for the project :) https://gitter.im/parrot-translate
